name: Daily Executor
on:
  schedule:
    - cron: "0 3 * * *"  # runs at 12:00 everyday (3:00 UTC)
  workflow_dispatch:
jobs:
  daily-executor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Set up pypi packages
        run: |
          pip install -r requirements.txt
      - name: Running main script
        id: run-main
        run: |
          python main.py
        env:
          SHEETDB_URL: ${{ secrets.SHEETDB_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: When job failed
        if: ${{ failure() && steps.run-main.outcome != 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "ghstarlog"
          SLACK_ICON_EMOJI: ":github:"
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Failed posting"
          MSG_MINIMAL: true
